--------------------------------------------------------
--  File created - pi¹tek-maj-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "STUDENT"."KLIENCI" 
   (	"ID_KLIENTA" NUMBER, 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(40 BYTE), 
	"NIP" NUMBER(10,0), 
	"NR_TELEFONU" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table LOKAL
--------------------------------------------------------

  CREATE TABLE "STUDENT"."LOKAL" 
   (	"ID_LOKALU" NUMBER, 
	"MIASTO" VARCHAR2(40 BYTE), 
	"ULICA" VARCHAR2(40 BYTE), 
	"NR_LOKALU" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table ODBIOR_SAMOCHODU
--------------------------------------------------------

  CREATE TABLE "STUDENT"."ODBIOR_SAMOCHODU" 
   (	"ID_ODBIORU" NUMBER, 
	"ID_WYDANIA" NUMBER, 
	"ID_PRACOWNIKA" NUMBER, 
	"DATA_ODBIORU_SAMOCHODU" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "STUDENT"."PRACOWNICY" 
   (	"ID_PRACOWNIKA" NUMBER, 
	"ID_LOKALU" NUMBER, 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(40 BYTE), 
	"ZAROBKI" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table REZERWACJA
--------------------------------------------------------

  CREATE TABLE "STUDENT"."REZERWACJA" 
   (	"ID_REZERWACJI" NUMBER, 
	"ID_KLIENTA" NUMBER, 
	"ID_SAMOCHODU" NUMBER, 
	"DATA_POCZATKU_WYPOZYCZENIA" DATE, 
	"DATA_KONCA_WYPOZYCZENIA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table SAMOCHODY
--------------------------------------------------------

  CREATE TABLE "STUDENT"."SAMOCHODY" 
   (	"ID_SAMOCHODU" NUMBER, 
	"ID_LOKALU" NUMBER, 
	"MARKA" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"ROK" NUMBER, 
	"KOLOR" VARCHAR2(20 BYTE), 
	"ILOSC_MIEJSC" NUMBER, 
	"POJEMNOSC_BAGAZNIKA" NUMBER, 
	"RODZAJ_SKRZYNI_BIEGOW" VARCHAR2(1 BYTE), 
	"CENA_ZA_DZIEN" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table WYDANIE_SAMOCHODU
--------------------------------------------------------

  CREATE TABLE "STUDENT"."WYDANIE_SAMOCHODU" 
   (	"ID_WYDANIA" NUMBER, 
	"ID_REZERWACJI" NUMBER, 
	"ID_PRACOWNIKA" NUMBER, 
	"DATA_WYDANIA_SAMOCHODU" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table WYPOZYCZENIE
--------------------------------------------------------

  CREATE TABLE "STUDENT"."WYPOZYCZENIE" 
   (	"ID_WYPOZYCZENIA" NUMBER, 
	"ID_ODBIORU" NUMBER, 
	"ZAROBEK" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
REM INSERTING into STUDENT.KLIENCI
SET DEFINE OFF;
REM INSERTING into STUDENT.LOKAL
SET DEFINE OFF;
REM INSERTING into STUDENT.ODBIOR_SAMOCHODU
SET DEFINE OFF;
REM INSERTING into STUDENT.PRACOWNICY
SET DEFINE OFF;
REM INSERTING into STUDENT.REZERWACJA
SET DEFINE OFF;
REM INSERTING into STUDENT.SAMOCHODY
SET DEFINE OFF;
REM INSERTING into STUDENT.WYDANIE_SAMOCHODU
SET DEFINE OFF;
REM INSERTING into STUDENT.WYPOZYCZENIE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index WYPOZYCZENIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."WYPOZYCZENIE_PK" ON "STUDENT"."WYPOZYCZENIE" ("ID_WYPOZYCZENIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index WYDANIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."WYDANIE_PK" ON "STUDENT"."WYDANIE_SAMOCHODU" ("ID_WYDANIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index SAMOCHODY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."SAMOCHODY_PK" ON "STUDENT"."SAMOCHODY" ("ID_SAMOCHODU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index REZERWACJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."REZERWACJA_PK" ON "STUDENT"."REZERWACJA" ("ID_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."PRACOWNICY_PK" ON "STUDENT"."PRACOWNICY" ("ID_PRACOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index ODBIOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."ODBIOR_PK" ON "STUDENT"."ODBIOR_SAMOCHODU" ("ID_ODBIORU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index LOKAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."LOKAL_PK" ON "STUDENT"."LOKAL" ("ID_LOKALU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index KLIENCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."KLIENCI_PK" ON "STUDENT"."KLIENCI" ("ID_KLIENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  Constraints for Table ODBIOR_SAMOCHODU
--------------------------------------------------------

  ALTER TABLE "STUDENT"."ODBIOR_SAMOCHODU" MODIFY ("DATA_ODBIORU_SAMOCHODU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."ODBIOR_SAMOCHODU" ADD CONSTRAINT "ODBIOR_PK" PRIMARY KEY ("ID_ODBIORU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REZERWACJA
--------------------------------------------------------

  ALTER TABLE "STUDENT"."REZERWACJA" ADD CONSTRAINT "REZERWACJA_PK" PRIMARY KEY ("ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SAMOCHODY
--------------------------------------------------------

  ALTER TABLE "STUDENT"."SAMOCHODY" MODIFY ("MARKA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SAMOCHODY" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SAMOCHODY" MODIFY ("CENA_ZA_DZIEN" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SAMOCHODY" MODIFY ("RODZAJ_SKRZYNI_BIEGOW" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SAMOCHODY" MODIFY ("ILOSC_MIEJSC" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SAMOCHODY" MODIFY ("ROK" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SAMOCHODY" ADD CHECK (rodzaj_skrzyni_biegow in ('A', 'M')) ENABLE;
  ALTER TABLE "STUDENT"."SAMOCHODY" ADD CONSTRAINT "SAMOCHODY_PK" PRIMARY KEY ("ID_SAMOCHODU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "STUDENT"."KLIENCI" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENCI" MODIFY ("NIP" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENCI" MODIFY ("NR_TELEFONU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENCI" ADD CONSTRAINT "KLIENCI_PK" PRIMARY KEY ("ID_KLIENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WYDANIE_SAMOCHODU
--------------------------------------------------------

  ALTER TABLE "STUDENT"."WYDANIE_SAMOCHODU" ADD CONSTRAINT "WYDANIE_PK" PRIMARY KEY ("ID_WYDANIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "STUDENT"."PRACOWNICY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."PRACOWNICY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_PK" PRIMARY KEY ("ID_PRACOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WYPOZYCZENIE
--------------------------------------------------------

  ALTER TABLE "STUDENT"."WYPOZYCZENIE" ADD CONSTRAINT "WYPOZYCZENIE_PK" PRIMARY KEY ("ID_WYPOZYCZENIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOKAL
--------------------------------------------------------

  ALTER TABLE "STUDENT"."LOKAL" MODIFY ("MIASTO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."LOKAL" MODIFY ("ULICA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."LOKAL" MODIFY ("NR_LOKALU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."LOKAL" ADD CONSTRAINT "LOKAL_PK" PRIMARY KEY ("ID_LOKALU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ODBIOR_SAMOCHODU
--------------------------------------------------------

  ALTER TABLE "STUDENT"."ODBIOR_SAMOCHODU" ADD CONSTRAINT "ODBIOR_FK_PRACOWNIK" FOREIGN KEY ("ID_PRACOWNIKA")
	  REFERENCES "STUDENT"."PRACOWNICY" ("ID_PRACOWNIKA") ENABLE;
  ALTER TABLE "STUDENT"."ODBIOR_SAMOCHODU" ADD CONSTRAINT "ODBIOR_FK_WYDANIE" FOREIGN KEY ("ID_WYDANIA")
	  REFERENCES "STUDENT"."WYDANIE_SAMOCHODU" ("ID_WYDANIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "STUDENT"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_FK" FOREIGN KEY ("ID_LOKALU")
	  REFERENCES "STUDENT"."LOKAL" ("ID_LOKALU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJA
--------------------------------------------------------

  ALTER TABLE "STUDENT"."REZERWACJA" ADD CONSTRAINT "REZERWACJA_FK" FOREIGN KEY ("ID_KLIENTA")
	  REFERENCES "STUDENT"."KLIENCI" ("ID_KLIENTA") ENABLE;
  ALTER TABLE "STUDENT"."REZERWACJA" ADD CONSTRAINT "REZERWACJA_FK2" FOREIGN KEY ("ID_SAMOCHODU")
	  REFERENCES "STUDENT"."SAMOCHODY" ("ID_SAMOCHODU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SAMOCHODY
--------------------------------------------------------

  ALTER TABLE "STUDENT"."SAMOCHODY" ADD CONSTRAINT "SAMOCHODY_FK" FOREIGN KEY ("ID_LOKALU")
	  REFERENCES "STUDENT"."LOKAL" ("ID_LOKALU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WYDANIE_SAMOCHODU
--------------------------------------------------------

  ALTER TABLE "STUDENT"."WYDANIE_SAMOCHODU" ADD CONSTRAINT "WYDANIE_FK_PRACOWNIK" FOREIGN KEY ("ID_PRACOWNIKA")
	  REFERENCES "STUDENT"."PRACOWNICY" ("ID_PRACOWNIKA") ENABLE;
  ALTER TABLE "STUDENT"."WYDANIE_SAMOCHODU" ADD CONSTRAINT "WYDANIE_FK_REZERWACJA" FOREIGN KEY ("ID_REZERWACJI")
	  REFERENCES "STUDENT"."REZERWACJA" ("ID_REZERWACJI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WYPOZYCZENIE
--------------------------------------------------------

  ALTER TABLE "STUDENT"."WYPOZYCZENIE" ADD CONSTRAINT "WYPOZYCZENIE_FK_ODBIOR" FOREIGN KEY ("ID_ODBIORU")
	  REFERENCES "STUDENT"."ODBIOR_SAMOCHODU" ("ID_ODBIORU") ENABLE;
