create table LOGOWANIE_PRACOWNICY
(
	ID_LOGOWANIE_PRACOWNICY NUMBER not null
		constraint ID_LOGOWANIE_PRACOWNICY_PK
			primary key,
	ID_PRACOWNIKA NUMBER
		constraint ID_PRACOWNIK_FK
			references PRACOWNICY,
	LOGIN VARCHAR2(20),
	HASLO VARCHAR2(20)
)
/

