create table WYDANIE_SAMOCHODU
(
	ID_WYDANIA NUMBER not null
		constraint WYDANIE_PK
			primary key,
	ID_REZERWACJI NUMBER
		constraint WYDANIE_FK_REZERWACJA
			references REZERWACJA,
	ID_PRACOWNIKA NUMBER
		constraint WYDANIE_FK_PRACOWNIK
			references PRACOWNICY,
	DATA_WYDANIA_SAMOCHODU DATE
)
/

